### PR TITLE
Upgrade Ember to 2.18

### PR DESCRIPTION
**Pull request by scottkidder**

### CODE REVIEW

**Comment by mnowik** [comment]
@scottkidder Sorry for the delay, will try to merge this in the next weeks

**Comment by mwpastore** [comment]
Should we also blast it with [codemod](https://github.com/ember-cli/ember-modules-codemod) as a part of this upgrade?

**Comment by olivierchatry** [comment]
Would be really nice to have :)

**Comment by scottkidder** [comment]
Ran codemod and qunit-codemod

**Comment by scottkidder** [comment]
x

**Comment by scottkidder** [comment]
misclick accidentally closed, reopening.

**Comment by danielspaniel** [comment]
Cheering you on from the sidelines  => for  this merge to happen  .. I will be 🕺  when you make a new release with this code

**Comment by scottkidder** [comment]
superseded by #10

**Pull request closed without merging**
