### PR TITLE
Support ISO alpha-3 codes

### PR DESCRIPTION
**Pull request by JCBarry**
Support the 3 character version of ISO country codes and implement convenience method to fetch country using ISO alpha-3 code.

ISO alpha3 is defined here: https://unstats.un.org/unsd/tradekb/Knowledgebase/50347/Country-Code

### CODE REVIEW

**Comment by mnowik** [comment]
@JCBarry Thanks a lot for the PR. I am currently working on a [branch](https://github.com/mnowik/ember-countries/tree/add-new-features) that is going to support ISO3.

I can ping you for the PR review if you want.

**Comment by JCBarry** [comment]
Hey there, not sure what your release plans are for the new branch, but I was hoping to use `ember-countries` in a project I'm working on currently.  Would it be possible to merge this PR in the short term while the new version is in the works -- unless you're thinking the new version can get shipped in a week or two?

Nice work on the lib and the new version looks great!

**Comment by mnowik** [comment]
@JCBarry I will release v2.0.0 next week. If I cannot make it I will ping you and we can merge your branch.

**Comment by mnowik** [comment]
@JCBarry I just merged my branch and bump the package version to 2.0.0. Thanks for your help.

**Pull request closed without merging**
